# Generated by Django 6.0.3 on 2026-04-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='alerta_7_dias_antes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='alerta_7_dias_depois',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='alerta_no_dia',
            field=models.BooleanField(default=False),
        ),
    ]
