# Generated by Django 6.0.3 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomanutencao',
            name='frequencia_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipomanutencao',
            name='frequencia_km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
