# Generated by Django 6.0.3 on 2026-05-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_manutencao_alerta_7_dias_antes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(default='', max_length=100),
        ),
    ]
