# Generated by Django 6.0.3 on 2026-05-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_veiculo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='alerta_atrasado',
            field=models.BooleanField(default=False),
        ),
    ]
